In [4]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [5]:
import undetected_chromedriver as uc

options = uc.ChromeOptions()
options.add_argument("--start-maximized")

driver = uc.Chrome(options=options)

In [5]:
driver.get(f"https://fbref.com/en/comps/9/Premier-League-Stats")

In [9]:
table = driver.find_element(By.CLASS_NAME, r'stats_table')

In [10]:
header = table.find_element(By.TAG_NAME, 'thead')
body = table.find_element(By.TAG_NAME, 'tbody')

In [ ]:
column_names = header.find_elements(By.TAG_NAME, 'th')

In [76]:
column_names = [i.text for i in column_names]

In [77]:
column_names

['Rk',
 'Squad',
 'MP',
 'W',
 'D',
 'L',
 'GF',
 'GA',
 'GD',
 'Pts',
 'Pts/MP',
 'Last 5',
 'Attendance',
 'Top Team Scorer',
 'Goalkeeper',
 'Notes']

In [1]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

def scrap_standing(url, league, season):

    driver.get(url)

    # Wait until Cloudflare check disappears and table becomes available
    wait = WebDriverWait(driver, 60)
    table = wait.until(
        EC.presence_of_element_located((By.CLASS_NAME, "stats_table"))
    )

    header = table.find_element(By.TAG_NAME, 'thead')
    body = table.find_element(By.TAG_NAME, 'tbody')

    column_names = [i.text for i in header.find_elements(By.TAG_NAME, 'th')]

    rows = []

    for i in body.find_elements(By.TAG_NAME, 'tr'):
        row = []
        row.append(i.find_element(By.TAG_NAME, 'th').text)

        row_values = i.find_elements(By.TAG_NAME, 'td')

        row.append(row_values[0].text)

        for j in row_values[1:]:
            row.append(j.text)

        rows.append(row)

    standings_df = pd.DataFrame(rows, columns=column_names)
    standings_df['Season'] = season
    standings_df['League'] = league[0]
    
    return standings_df

In [6]:
sample_data = scrap_standing(f"https://fbref.com/en/comps/9/Premier-League-Stats", "PL", 2021)

In [7]:
sample_data

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes,Season,League
0,1,Manchester City,33,21,7,5,66,29,+37,70,2.12,D D W W W,"52,219",Erling Haaland - 24,Gianluigi Donnarumma,,2021,P
1,2,Arsenal,33,21,7,5,63,26,+37,70,2.12,W W W L L,"60,216",Viktor Gyökeres - 12,David Raya,,2021,P
2,3,Manchester Utd,33,16,10,7,58,45,+13,58,1.76,L W D L W,"73,964","Bryan Mbeumo, Benjamin Šeško - 9",Senne Lammens,,2021,P
3,4,Aston Villa,33,17,7,9,47,41,+6,58,1.76,L L W D W,"41,885",Ollie Watkins - 11,Emiliano Martínez,,2021,P
4,5,Liverpool,33,16,7,10,54,43,+11,55,1.67,L D L W W,"60,370",Hugo Ekitike - 11,Alisson,,2021,P
5,6,Brighton,34,13,11,10,48,39,+9,50,1.47,W W W D W,"31,356",Danny Welbeck - 13,Bart Verbruggen,,2021,P
6,7,Bournemouth,34,11,16,7,52,52,0,49,1.44,D D W W D,"11,175",Eli Junior Kroupi - 11,Đorđe Petrović,,2021,P
7,8,Chelsea,34,13,9,12,53,45,+8,48,1.41,L L L L L,"39,601",João Pedro - 14,Robert Sánchez,,2021,P
8,9,Brentford,33,13,9,11,48,44,+4,48,1.45,D D D D D,"17,117",Igor Thiago - 21,Caoimhín Kelleher,,2021,P
9,10,Everton,33,13,8,12,40,39,+1,47,1.42,W L W D L,"52,163",Beto - 8,Jordan Pickford,,2021,P
10,11,Sunderland,33,12,10,11,36,40,-4,46,1.39,W L W W L,"46,366",Brian Brobbey - 6,Robin Roefs,,2021,P
11,12,Fulham,33,13,6,14,43,46,-3,45,1.36,L D W L D,"27,136",Harry Wilson - 10,Bernd Leno,,2021,P
12,13,Crystal Palace,32,11,10,11,35,36,-1,43,1.34,L W D W D,"24,988",Jean-Philippe Mateta - 10,Dean Henderson,,2021,P
13,14,Newcastle United,33,12,6,15,46,49,-3,42,1.27,W W L L L,"52,103",Bruno Guimarães - 9,Nick Pope,,2021,P
14,15,Leeds United,34,9,13,12,44,51,-7,40,1.18,D D W W D,"36,709",Dominic Calvert-Lewin - 11,Karl Darlow,,2021,P
15,16,Nottingham Forest,33,9,9,15,36,45,-9,36,1.09,D D W D W,"30,391",Morgan Gibbs-White - 12,Matz Sels,,2021,P
16,17,West Ham United,33,8,9,16,40,57,-17,33,1.00,W D L W D,"62,455",Jarrod Bowen - 8,Alphonse Areola,,2021,P
17,18,Tottenham Hotspur,33,7,10,16,42,53,-11,31,0.94,L D L L D,"60,952",Richarlison - 9,Guglielmo Vicario,,2021,P
18,19,Burnley,34,4,8,22,34,68,-34,20,0.59,D L L L L,"20,990",Zian Flemming - 9,Martin Dúbravka,,2021,P
19,20,Wolves,33,3,8,22,24,61,-37,17,0.52,W W D L L,"29,851","Tolu Arokodare, Rodrigo Gomes - 3",José Sá,,2021,P

In [8]:
driver.close()

In [99]:
for i in leagues.items():
    print(i)

('Premier League', (9, 'Premier-League'))
('La Liga', (12, 'La-Liga'))
('Serie A', (11, 'Serie-A'))
('Bundesliga', (20, 'Bundesliga'))
('Ligue 1', (13, 'Ligue-1'))

In [97]:
import undetected_chromedriver as uc

options = uc.ChromeOptions()
options.add_argument("--start-maximized")

driver = uc.Chrome(options=options)

In [100]:
leagues = {
    "Premier League": (9, "Premier-League"),
    "La Liga": (12, "La-Liga"),
    "Serie A": (11, "Serie-A"),
    "Bundesliga": (20, "Bundesliga"),
    "Ligue 1": (13, "Ligue-1")
}

In [ ]:
"premier league 2016"

In [ ]:
leagues_dict = {}

for league in leagues.items():
    for season in range(2016, 2026, 1):
        print(f"League: {league[0]}, Season: {season}")
        base_url = f"https://fbref.com/en/comps/{league[1][0]}/{season-1}-{season}/{season-1}-{season}-{league[1][1]}-Stats"

        data = scrap_standing(base_url, league[0], season)

        leagues_dict[str(league[0])+str(season)] = data
        print(f'Scraping {league[0]} {season} done')

    print("\n\n")

league_dict_values = list(leagues_dict.values())

leagues_df = league_dict_values[0]

for i in league_dict_values[1:]:
    leagues_df = pd.concat([leagues_df, i])

League: Premier League, Season: 2016
Scraping Premier League2016 done
League: Premier League, Season: 2017
Scraping Premier League2017 done
League: Premier League, Season: 2018
Scraping Premier League2018 done
League: Premier League, Season: 2019
Scraping Premier League2019 done
League: Premier League, Season: 2020
Scraping Premier League2020 done
League: Premier League, Season: 2021
Scraping Premier League2021 done
League: Premier League, Season: 2022
Scraping Premier League2022 done
League: Premier League, Season: 2023
Scraping Premier League2023 done
League: Premier League, Season: 2024
Scraping Premier League2024 done
League: Premier League, Season: 2025
Scraping Premier League2025 done

League: La Liga, Season: 2016
Scraping La Liga2016 done
League: La Liga, Season: 2017
Scraping La Liga2017 done
League: La Liga, Season: 2018
Scraping La Liga2018 done
League: La Liga, Season: 2019
Scraping La Liga2019 done
League: La Liga, Season: 2020
Scraping La Liga2020 done
League: La Liga, Season: 2021
Scraping La Liga2021 done
League: La Liga, Season: 2022
Scraping La Liga2022 done
League: La Liga, Season: 2023
Scraping La Liga2023 done
League: La Liga, Season: 2024
Scraping La Liga2024 done
League: La Liga, Season: 2025
Scraping La Liga2025 done

League: Serie A, Season: 2016
Scraping Serie A2016 done
League: Serie A, Season: 2017
Scraping Serie A2017 done
League: Serie A, Season: 2018
Scraping Serie A2018 done
League: Serie A, Season: 2019
Scraping Serie A2019 done
League: Serie A, Season: 2020
Scraping Serie A2020 done
League: Serie A, Season: 2021
Scraping Serie A2021 done
League: Serie A, Season: 2022
Scraping Serie A2022 done
League: Serie A, Season: 2023
Scraping Serie A2023 done
League: Serie A, Season: 2024
Scraping Serie A2024 done
League: Serie A, Season: 2025
Scraping Serie A2025 done

League: Bundesliga, Season: 2016
Scraping Bundesliga2016 done
League: Bundesliga, Season: 2017
Scraping Bundesliga2017 done
League: Bundesliga, Season: 2018
Scraping Bundesliga2018 done
League: Bundesliga, Season: 2019
Scraping Bundesliga2019 done
League: Bundesliga, Season: 2020
Scraping Bundesliga2020 done
League: Bundesliga, Season: 2021
Scraping Bundesliga2021 done
League: Bundesliga, Season: 2022
Scraping Bundesliga2022 done
League: Bundesliga, Season: 2023
Scraping Bundesliga2023 done
League: Bundesliga, Season: 2024
Scraping Bundesliga2024 done
League: Bundesliga, Season: 2025
Scraping Bundesliga2025 done

League: Ligue 1, Season: 2016
Scraping Ligue 12016 done
League: Ligue 1, Season: 2017
Scraping Ligue 12017 done
League: Ligue 1, Season: 2018
Scraping Ligue 12018 done
League: Ligue 1, Season: 2019
Scraping Ligue 12019 done
League: Ligue 1, Season: 2020
Scraping Ligue 12020 done
League: Ligue 1, Season: 2021
Scraping Ligue 12021 done
League: Ligue 1, Season: 2022
Scraping Ligue 12022 done
League: Ligue 1, Season: 2023
Scraping Ligue 12023 done
League: Ligue 1, Season: 2024
Scraping Ligue 12024 done
League: Ligue 1, Season: 2025
Scraping Ligue 12025 done

ValueError: If using all scalar values, you must pass an index

In [129]:
leagues_df

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper,Notes,Season
0,1,Leicester City,38,23,12,3,68,36,+32,81,2.13,"32,021",Jamie Vardy - 24,Kasper Schmeichel,→ Champions League via league finish,2016
1,2,Arsenal,38,20,11,7,65,36,+29,71,1.87,"59,944",Olivier Giroud - 16,Petr Čech,→ Champions League via league finish,2016
2,3,Tottenham Hotspur,38,19,13,6,69,35,+34,70,1.84,"35,776",Harry Kane - 25,Hugo Lloris,→ Champions League via league finish,2016
3,4,Manchester City,38,19,9,10,71,41,+30,66,1.74,"54,041",Sergio Agüero - 24,Joe Hart,→ Champions League via league finish,2016
4,5,Manchester Utd,38,19,9,10,49,35,+14,66,1.74,"75,279",Anthony Martial - 11,David de Gea,→ Europa League via cup win 1,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,14,Angers,34,10,6,18,32,53,-21,36,1.06,"13,142",Esteban Lepaul - 9,Yahia Fofana,,2025
14,15,Le Havre,34,10,4,20,40,71,-31,34,1.00,"20,218",Abdoulaye Touré - 10,Arthur Desmas,,2025
15,16,Reims,34,8,9,17,33,47,-14,33,0.97,"15,655",Keito Nakamura - 11,Yehvann Diouf,→ French 1/2 Relegation/Promotion play-offs,2025
16,17,Saint-Étienne,34,8,6,20,39,77,-38,30,0.88,"30,220",Lucas Stassin - 12,Gautier Larsonneur,Relegated,2025
17,18,Montpellier,34,4,4,26,23,79,-56,16,0.47,"13,483",Arnaud Nordin - 4,Benjamin Lecomte,Relegated,2025

In [113]:
"dasd" + "asdad"

'dasdasdad'

In [9]:
import soccerdata as sd

[04/23/26 21:40:11] INFO     No custom team name replacements found. You can configure these in       ]8;id=15493449;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=15493450;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py#92\92]8;;\
                             C:\Users\bodyk\soccerdata\config\teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=15493456;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=15493457;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py#190\190]8;;\
                             C:\Users\bodyk\soccerdata\config\league_dict.json.

In [ ]:
sd.

In [12]:
matches = sd.FBref(leagues=["ENG-Premier League", "ESP-La Liga", "ITA-Serie A", "GER-Bundesliga", "FRA-Ligue 1"], seasons=list(range(2016, 2026, 1)))

[04/23/26 21:43:55] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=15493478;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=15493479;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

In [13]:
matches = matches.read_team_match_stats()

KeyboardInterrupt:

In [ ]:
matches

In [ ]:
matches.to_csv("Scrapped_date/matches_table.csv")

In [37]:
season_2021 = fbref.read_team_match_stats()

In [46]:
season_2021.columns

Index(['date', 'time', 'round', 'day', 'venue', 'result', 'GF', 'GA',
       'opponent', 'Poss', 'Attendance', 'Captain', 'Formation',
       'Opp Formation', 'Referee', 'match_report', 'Notes'],
      dtype='object')

In [61]:
season_2021['Formation'].unique()

<StringArray>
['3-1-4-2',   '3-5-2',   '4-4-2', '3-4-1-2', '4-1-4-1',   '4-5-1',   '4-3-3',
 '4-2-3-1',   '3-4-3',   '5-3-2', '4-3-2-1', '4-4-1-1',  '4-4-2◆', '4-1-3-2',
   '5-4-1', '4-3-1-2', '4-2-2-2']
Length: 17, dtype: string

,gender,governing_body,first_season,last_season,tier,awards,url,country
league,,,,,,,,
ESP-La Liga,M,<NA>,8889,2526,1st,"La Liga Best Player, Trofeo Alfredo Di Stéfano",/en/comps/12/history/La-Liga-Seasons,ESP

In [35]:
season_2021

                                   players_used   Age  Poss Playing Time  \
                                                                      MP
league      season team
ESP-La Liga 2021   Alavés                    30  28.7  42.8           38
                   Athletic Club             27  26.6  49.9           38
                   Atlético Madrid           25  27.3  52.3           38
                   Barcelona                 25  26.4  65.5           38
                   Celta Vigo                30  26.6  53.3           38
                   Cádiz                     34  28.8  34.8           38
                   Eibar                     30  28.2  49.3           38
                   Elche                     30  28.1  47.5           38
                   Getafe                    31  26.7  43.3           38
                   Granada                   34  27.4  41.4           38
                   Huesca                    27  28.0  48.3           38
                   Levante                   29  28.0  52.2           38
                   Osasuna                   28  27.9  43.2           38
                   Real Betis                25  27.9  53.6           38
                   Real Madrid               30  27.9  59.3           38
                   Real Sociedad             30  25.0  54.9           38
                   Sevilla                   26  28.1  60.9           38
                   Valencia                  30  25.2  46.9           38
                   Valladolid                32  28.1  45.2           38
                   Villarreal                29  28.0  55.2           38

                                                    Performance           ...  \
                                   Starts   Min 90s         Gls Ast  G+A  ...
league      season team                                                   ...
ESP-La Liga 2021   Alavés             418  3420  38          35  21   56  ...
                   Athletic Club      418  3420  38          43  31   74  ...
                   Atlético Madrid    418  3420  38          65  54  119  ...
                   Barcelona          418  3420  38          80  51  131  ...
                   Celta Vigo         418  3420  38          55  39   94  ...
                   Cádiz              418  3420  38          33  16   49  ...
                   Eibar              418  3420  38          29  20   49  ...
                   Elche              418  3420  38          33  25   58  ...
                   Getafe             418  3420  38          27  14   41  ...
                   Granada            418  3420  38          47  30   77  ...
                   Huesca             418  3420  38          32  23   55  ...
                   Levante            418  3420  38          45  35   80  ...
                   Osasuna            418  3420  38          36  25   61  ...
                   Real Betis         418  3420  38          50  35   85  ...
                   Real Madrid        418  3420  38          64  53  117  ...
                   Real Sociedad      418  3420  38          58  39   97  ...
                   Sevilla            418  3420  38          52  36   88  ...
                   Valencia           418  3420  38          48  35   83  ...
                   Valladolid         418  3420  38          34  21   55  ...
                   Villarreal         418  3420  38          57  33   90  ...

                                                       Per 90 Minutes        \
                                    PK PKatt CrdY CrdR            Gls   Ast
league      season team
ESP-La Liga 2021   Alavés            5     8   96    8           0.92  0.55
                   Athletic Club     4     5   82    3           1.13  0.82
                   Atlético Madrid   5     7  100    0           1.71  1.42
                   Barcelona         4     8   72    2           2.11  1.34
                   Celta Vigo        7     7  109    5           1.45  1.03
                   Cádiz             4     4   81    3           0.87  0.42
                   Eibar             4     9   71    3           0.76  0.53
                   Elche             2     3   99    3           0.87  0.66
                   Getafe            3     5  120    7           0.71  0.37
                   Granada           3     5   97    6           1.24  0.79
                   Huesca            3     4   69    2           0.84  0.61
                   Levante           3     6   68    1           1.18  0.92
                   Osasuna           5     6   80    5           0.95  0.66
                   Real Betis        8    11   93    8           1.32  0.92
                   Real Madrid       3     3   59    2           1.68  1.39
                   Real Sociedad     9    12   81    1           1.53  1.03
                   Sevilla           6     7   79    2           1.37  0.95
                   Valencia          8    10   82    5           1.26  0.92
                   Valladolid        7     8   93    4           0.89  0.55
                   Villarreal       12    13   67    5            1.5  0.87

                                                       \
                                     G+A  G-PK G+A-PK
league      season team
ESP-La Liga 2021   Alavés           1.47  0.79   1.34
                   Athletic Club    1.95  1.03   1.84
                   Atlético Madrid  3.13  1.58    3.0
                   Barcelona        3.45   2.0   3.34
                   Celta Vigo       2.47  1.26   2.29
                   Cádiz            1.29  0.76   1.18
                   Eibar            1.29  0.66   1.18
                   Elche            1.53  0.82   1.47
                   Getafe           1.08  0.63    1.0
                   Granada          2.03  1.16   1.95
                   Huesca           1.45  0.76   1.37
                   Levante          2.11  1.11   2.03
                   Osasuna          1.61  0.82   1.47
                   Real Betis       2.24  1.11   2.03
                   Real Madrid      3.08  1.61    3.0
                   Real Sociedad    2.55  1.29   2.32
                   Sevilla          2.32  1.21   2.16
                   Valencia         2.18  1.05   1.97
                   Valladolid       1.45  0.71   1.26
                   Villarreal       2.37  1.18   2.05

                                                                                  url

league      season team
ESP-La Liga 2021   Alavés                  /en/squads/8d6fd021/2020-2021/Alaves-Stats
                   Athletic Club    /en/squads/2b390eca/2020-2021/Athletic-Club-Stats
                   Atlético Madrid  /en/squads/db3b9613/2020-2021/Atletico-Madrid-...
                   Barcelona            /en/squads/206d90db/2020-2021/Barcelona-Stats
                   Celta Vigo          /en/squads/f25da7fb/2020-2021/Celta-Vigo-Stats
                   Cádiz                    /en/squads/ee7c297c/2020-2021/Cadiz-Stats
                   Eibar                    /en/squads/bea5c710/2020-2021/Eibar-Stats
                   Elche                    /en/squads/6c8b07df/2020-2021/Elche-Stats
                   Getafe                  /en/squads/7848bd64/2020-2021/Getafe-Stats
                   Granada                /en/squads/a0435291/2020-2021/Granada-Stats
                   Huesca                  /en/squads/c6c493e6/2020-2021/Huesca-Stats
                   Levante                /en/squads/9800b6a1/2020-2021/Levante-Stats
                   Osasuna                /en/squads/03c57e2b/2020-2021/Osasuna-Stats
                   Real Betis          /en/squads/fc536746/2020-2021/Real-Betis-Stats
                   Real Madrid        /en/squads/53a2f082/2020-2021/Real-Madrid-Stats
                   Real Sociedad    /en/squads/e31d1cd9/2020-2021/Real-Sociedad-Stats
                   Sevilla                /en/squads/ad2be733/2020-2021/Sevilla-Stats
                   Valencia              /en/squads/dcc91a7b/2020-2021/Valencia-Stats
                   Valladolid          /en/squads/17859612/2020-2021/Valladolid-Stats
                   Villarreal          /en/squads/2a8183b3/2020-2021/Villarreal-Stats

[20 rows x 21 columns]

In [34]:
season_2021.columns

MultiIndex([(  'players_used',       ''),
            (           'Age',       ''),
            (          'Poss',       ''),
            (  'Playing Time',     'MP'),
            (  'Playing Time', 'Starts'),
            (  'Playing Time',    'Min'),
            (  'Playing Time',    '90s'),
            (   'Performance',    'Gls'),
            (   'Performance',    'Ast'),
            (   'Performance',    'G+A'),
            (   'Performance',   'G-PK'),
            (   'Performance',     'PK'),
            (   'Performance',  'PKatt'),
            (   'Performance',   'CrdY'),
            (   'Performance',   'CrdR'),
            ('Per 90 Minutes',    'Gls'),
            ('Per 90 Minutes',    'Ast'),
            ('Per 90 Minutes',    'G+A'),
            ('Per 90 Minutes',   'G-PK'),
            ('Per 90 Minutes', 'G+A-PK'),
            (           'url',       '')],
           )

In [25]:
espn.

In [24]:
epl_schedule.tail()

                                                                                            date  \
league             season game
ENG-Premier League 2627   2026-05-24 Manchester City-Aston Villa       2026-05-24 15:00:00+00:00
                          2026-05-24 Nottingham Forest-AFC Bournemouth 2026-05-24 15:00:00+00:00
                          2026-05-24 Sunderland-Chelsea                2026-05-24 15:00:00+00:00
                          2026-05-24 Tottenham Hotspur-Everton         2026-05-24 15:00:00+00:00
                          2026-05-24 West Ham United-Leeds United      2026-05-24 15:00:00+00:00

                                                                                home_team  \
league             season game
ENG-Premier League 2627   2026-05-24 Manchester City-Aston Villa          Manchester City
                          2026-05-24 Nottingham Forest-AFC Bournemouth  Nottingham Forest
                          2026-05-24 Sunderland-Chelsea                        Sunderland
                          2026-05-24 Tottenham Hotspur-Everton          Tottenham Hotspur
                          2026-05-24 West Ham United-Leeds United         West Ham United

                                                                              away_team  \
league             season game
ENG-Premier League 2627   2026-05-24 Manchester City-Aston Villa            Aston Villa
                          2026-05-24 Nottingham Forest-AFC Bournemouth  AFC Bournemouth
                          2026-05-24 Sunderland-Chelsea                         Chelsea
                          2026-05-24 Tottenham Hotspur-Everton                  Everton
                          2026-05-24 West Ham United-Leeds United          Leeds United

                                                                        game_id  \
league             season game
ENG-Premier League 2627   2026-05-24 Manchester City-Aston Villa         740970
                          2026-05-24 Nottingham Forest-AFC Bournemouth   740972
                          2026-05-24 Sunderland-Chelsea                  740973
                          2026-05-24 Tottenham Hotspur-Everton           740974
                          2026-05-24 West Ham United-Leeds United        740971

                                                                       league_id
league             season game
ENG-Premier League 2627   2026-05-24 Manchester City-Aston Villa           eng.1
                          2026-05-24 Nottingham Forest-AFC Bournemouth     eng.1
                          2026-05-24 Sunderland-Chelsea                    eng.1
                          2026-05-24 Tottenham Hotspur-Everton             eng.1
                          2026-05-24 West Ham United-Leeds United          eng.1

In [72]:
leagues = ["PL", "LL", "SA", "BL1", "FL1"]
league_names = ["Premier League", "La Liga", "Serie A", "Bundsliga", "Ligue 1"]
countries = ["England", "Spain", "Italy", "Germany", "France"]
seasons = list(range(2025, 2015, -1))

league_table = pd.DataFrame({
    "League_id": leagues * len(seasons),
    "League_name": league_names * len(seasons),
    "Country": countries * len(seasons),
    "Season_year": [s for s in seasons for _ in leagues]
})

In [73]:
league_table.sort_values(by=["League_name", "Season_year"])

   League_id     League_name  Country  Season_year
48       BL1       Bundsliga  Germany         2016
43       BL1       Bundsliga  Germany         2017
38       BL1       Bundsliga  Germany         2018
33       BL1       Bundsliga  Germany         2019
28       BL1       Bundsliga  Germany         2020
23       BL1       Bundsliga  Germany         2021
18       BL1       Bundsliga  Germany         2022
13       BL1       Bundsliga  Germany         2023
8        BL1       Bundsliga  Germany         2024
3        BL1       Bundsliga  Germany         2025
46        LL         La Liga    Spain         2016
41        LL         La Liga    Spain         2017
36        LL         La Liga    Spain         2018
31        LL         La Liga    Spain         2019
26        LL         La Liga    Spain         2020
21        LL         La Liga    Spain         2021
16        LL         La Liga    Spain         2022
11        LL         La Liga    Spain         2023
6         LL         La Liga    Spain         2024
1         LL         La Liga    Spain         2025
49       FL1         Ligue 1   France         2016
44       FL1         Ligue 1   France         2017
39       FL1         Ligue 1   France         2018
34       FL1         Ligue 1   France         2019
29       FL1         Ligue 1   France         2020
24       FL1         Ligue 1   France         2021
19       FL1         Ligue 1   France         2022
14       FL1         Ligue 1   France         2023
9        FL1         Ligue 1   France         2024
4        FL1         Ligue 1   France         2025
45        PL  Premier League  England         2016
40        PL  Premier League  England         2017
35        PL  Premier League  England         2018
30        PL  Premier League  England         2019
25        PL  Premier League  England         2020
20        PL  Premier League  England         2021
15        PL  Premier League  England         2022
10        PL  Premier League  England         2023
5         PL  Premier League  England         2024
0         PL  Premier League  England         2025
47        SA         Serie A    Italy         2016
42        SA         Serie A    Italy         2017
37        SA         Serie A    Italy         2018
32        SA         Serie A    Italy         2019
27        SA         Serie A    Italy         2020
22        SA         Serie A    Italy         2021
17        SA         Serie A    Italy         2022
12        SA         Serie A    Italy         2023
7         SA         Serie A    Italy         2024
2         SA         Serie A    Italy         2025

In [ ]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

import soccerdata as sd
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

leagues = [
    "ENG-Premier League",
    "ESP-La Liga",
    "ITA-Serie A",
    "GER-Bundesliga",
    "FRA-Ligue 1"
]

seasons = list(range(2016, 2026))

def fetch_data(league, season):
    try:
        fbref = sd.FBref(leagues=[league], seasons=[season])
        df = fbref.read_team_match_stats()
        df["league"] = league
        df["season"] = season
        return df
    except Exception as e:
        print(f"Error for {league} {season}: {e}")
        return None


tasks = [(league, season) for league in leagues for season in seasons]
results = []

with ThreadPoolExecutor(max_workers=10) as executor:
    futures = {executor.submit(fetch_data, l, s): (l, s) for l, s in tasks}

    for future in tqdm(as_completed(futures), total=len(futures), desc="Scraping FBref"):
        res = future.result()
        if res is not None:
            results.append(res)

matches = pd.concat(results, ignore_index=True)

matches.to_csv("Scrapped_date/matches_table.csv", index=False)

[04/23/26 23:16:08] INFO     No custom team name replacements found. You can configure these in       ]8;id=3654067;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=3654068;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py#92\92]8;;\
                             C:\Users\bodyk\soccerdata\config\teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=3654074;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=3654075;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py#190\190]8;;\
                             C:\Users\bodyk\soccerdata\config\league_dict.json.

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654082;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654083;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654088;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654089;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654094;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654095;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654100;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654101;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654106;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654107;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654112;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654113;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654118;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654119;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654124;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654125;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654130;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654131;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654136;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654137;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

Scraping FBref:   0%|          | 0/50 [00:00<?, ?it/s]

[04/23/26 23:16:20] WARNING  c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packag ]8;id=3654144;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\warnings.py\warnings.py]8;;\:]8;id=3654145;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\warnings.py#109\109]8;;\
                             es\soccerdata\_common.py:144: UserWarning: Season id "2021" is
                             ambiguous: interpreting as "20-21"
                               warnings.warn(msg, stacklevel=1)

[04/23/26 23:16:21] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654150;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654151;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

Scraping FBref:   2%|▏         | 1/50 [00:12<10:18, 12.63s/it]

[04/23/26 23:16:25] ERROR    Error while scraping                                                    ]8;id=3654157;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654158;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#623\623]8;;\
                             https://fbref.com/en/squads/18bb7c10/2025-2026/matchlogs/all_comps/sche
                             dule. Retrying in 0 seconds... (attempt 1 of 5).
                             Traceback (most recent call last):
                               File
                             "c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\soccerdata\_common.py", line 603, in _download_and_save
                                 self._driver.get(url)
                               File
                             "c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\seleniumbase\core\browser_launcher.py", line 5934, in <lambda>
                                 driver.get = lambda url: uc_special_open_if_cf(
                               File
                             "c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\seleniumbase\core\browser_launcher.py", line 543, in
                             uc_special_open_if_cf
                                 driver, driver.window_handles[-1], 2
                               File
                             "c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\seleniumbase\undetected\__init__.py", line 350, in __getattribute__
                                 return super().__getattribute__(item)
                               File
                             "c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\selenium\webdriver\remote\webdriver.py", line 591, in window_handles
                                 return self.execute(Command.W3C_GET_WINDOW_HANDLES)["value"]
                               File
                             "c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\selenium\webdriver\remote\webdriver.py", line 450, in execute
                                 self.error_handler.check_response(response)
                               File
                             "c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packag
                             es\selenium\webdriver\remote\errorhandler.py", line 232, in
                             check_response
                                 raise exception_class(message, screen, stacktrace)
                             selenium.common.exceptions.InvalidSessionIdException: Message: invalid
                             session id; For documentation on this error, please visit:
                             https://www.selenium.dev/documentation/webdriver/troubleshooting/errors
                             #invalidsessionidexception
                             Stacktrace:
                                     uc_driver!GetHandleVerifier [0x7ff6df34a8e5+14e45]
                                     uc_driver!GetHandleVerifier [0x7ff6df34a950+14eb0]
                                     uc_driver!(No symbol) [0x7ff6df0bd4d6]
                                     uc_driver!(No symbol) [0x7ff6df108166]
                                     uc_driver!(No symbol) [0x7ff6df13ff32]
                                     uc_driver!(No symbol) [0x7ff6df13a191]
                                     uc_driver!(No symbol) [0x7ff6df139433]
                                     uc_driver!(No symbol) [0x7ff6df086005]
                                     uc_driver!GetHandleVerifier [0x7ff6df660149+32a6a9]
                                     uc_driver!GetHandleVerifier [0x7ff6df65a715+324c75]
                                     uc_driver!GetHandleVerifier [0x7ff6df67c012+346572]
                                     uc_driver!GetHandleVerifier [0x7ff6df367cb5+32215]
                                     uc_driver!GetHandleVerifier [0x7ff6df37087c+3addc]
                                     uc_driver!(No symbol) [0x7ff6df084d9a]
                                     uc_driver!GetHandleVerifier [0x7ff6df7c60a8+490608]
                                     KERNEL32!BaseThreadInitThunk [0x7ffb947ae8d7+17]
                                     ntdll!RtlUserThreadStart [0x7ffb94eec3fc+2c]

Scraping FBref:   4%|▍         | 2/50 [00:19<07:15,  9.07s/it]

[04/23/26 23:16:28] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654163;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654164;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

Scraping FBref:   6%|▌         | 3/50 [00:22<05:10,  6.60s/it]

[04/23/26 23:16:31] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654169;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654170;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

Scraping FBref:   8%|▊         | 4/50 [00:23<03:12,  4.19s/it]

[04/23/26 23:16:32] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654175;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654176;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

Scraping FBref:  10%|█         | 5/50 [00:24<02:23,  3.19s/it]

[04/23/26 23:16:33] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654181;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654182;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

Scraping FBref:  12%|█▏        | 6/50 [00:29<02:47,  3.80s/it]

[04/23/26 23:16:38] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654187;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654188;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

Scraping FBref:  12%|█▏        | 6/50 [00:30<03:43,  5.09s/it]

[04/23/26 23:16:39] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654193;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654194;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654199;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654200;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

[04/23/26 23:16:40] WARNING  c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packag ]8;id=3654205;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\warnings.py\warnings.py]8;;\:]8;id=3654206;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\warnings.py#109\109]8;;\
                             es\soccerdata\_common.py:144: UserWarning: Season id "2021" is
                             ambiguous: interpreting as "20-21"
                               warnings.warn(msg, stacklevel=1)

[04/23/26 23:16:41] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654211;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654212;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654217;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654218;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

[04/23/26 23:16:42] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654223;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654224;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654229;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654230;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\

[04/23/26 23:16:43] INFO     Saving cached data to C:\Users\bodyk\soccerdata\data\FBref              ]8;id=3654235;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=3654236;file://c:\Users\bodyk\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#250\250]8;;\